version: '2'
services:
  seleniumhub:
    image: selenium/hub
    environment:
      - GRID_MAX_SESSION=5
    ports:
      - 4444:4444

  firefoxnode:
    image: selenium/node-firefox
    restart: always
    # https://github.com/SeleniumHQ/docker-selenium/issues/133
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    links:
      - seleniumhub:hub

  chromenode:
    image: selenium/node-chrome
    restart: always
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    links:
      - seleniumhub:hub

  pytest:
    build:
      context: ./
      dockerfile: ./docker/python/Dockerfile
    volumes:
      - ./storage/logs:/reports
      - ./storage/tests:/storage
    links:
      - seleniumhub:hub
